### PR TITLE
straighten indent

### PR DESCRIPTION
**Pull request by mtbc**
Trivial whitespace fix, see diff.

### CODE REVIEW

**Comment by mtbc** [comment]
> Error: Bundler "DMG Installer" (dmg) failed to produce a bundle.

**Comment by joshmoore** [comment]
Very odd.

<details><summary>Details:</summary>
<p>

```
> Task :packageApplicationDmg

No base JDK. Package will use system JRE.

No base JDK. Package will use system JRE.

Version strings can consist of only numbers and up to two dots.

java.lang.NumberFormatException: Illegal embedded sign character

	at java.math.BigInteger.<init>(BigInteger.java:428)

	at java.math.BigInteger.<init>(BigInteger.java:606)

	at com.oracle.tools.packager.mac.MacAppBundler.validCFBundleVersion(MacAppBundler.java:330)

	at com.oracle.tools.packager.mac.MacAppBundler.lambda$static$199(MacAppBundler.java:167)

	at com.oracle.tools.packager.BundlerParamInfo.fetchFrom(BundlerParamInfo.java:132)

	at com.oracle.tools.packager.mac.MacAppBundler.doValidate(MacAppBundler.java:396)

	at com.oracle.tools.packager.mac.MacBaseInstallerBundler.validateAppImageAndBundeler(MacBaseInstallerBundler.java:199)

	at com.oracle.tools.packager.mac.MacDmgBundler.validate(MacDmgBundler.java:511)

	at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:351)

	at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:319)

	at com.sun.javafx.tools.packager.Main.main(Main.java:476)

Building DMG package for OMERO.insight

Preparing Info.plist: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/macosx/Info.plist

  Using default package resource [Bundle config file]  (add package/macosx/Info.plist to the class path to customize)

   Using custom package resource [icon]  (loaded from file /Users/travis/build/ome/omero-insight/icons/omeroInsight.icns)

  Config files are saved to /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/macosx. Use them to customize package.

  Using default package resource [dmg background]  (add package/macosx/OMERO.insight-background.png to the class path to customize)

   Using custom package resource [volume icon]  (loaded from file /Users/travis/build/ome/omero-insight/icons/omeroInsight.icns)

Using default package resource [script to run after application image is populated]  (add package/macosx/OMERO.insight-post-image.sh to the class path to customize)

Preparing dmg setup: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/macosx/OMERO.insight-dmg-setup.scpt

  Using default package resource [DMG setup script]  (add package/macosx/OMERO.insight-dmg-setup.scpt to the class path to customize)

 Creating DMG file: /Users/travis/build/ome/omero-insight/build/packaged/main/bundles/OMERO.insight-5.5.0-m3.dmg

Running [/usr/bin/hdiutil, create, -quiet, -srcfolder, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/image-5329980585473428736, -volname, OMERO.insight, -ov, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight-tmp.dmg, -format, UDRW]

Running [/usr/bin/hdiutil, attach, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight-tmp.dmg, -quiet, -mountroot, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images]

Running [/usr/bin/SetFile, -c, icnC, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight/.VolumeIcon.icns]

Running [/usr/bin/SetFile, -a, C, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight]

ERROR: Unexpected Error. (-50)  on file: /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight 

java.io.IOException: Exec failed with code 2 command [[/usr/bin/SetFile, -a, C, /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/images/OMERO.insight] in unspecified directory

	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:165)

	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:138)

	at com.oracle.tools.packager.IOUtils.exec(IOUtils.java:132)

	at com.oracle.tools.packager.mac.MacDmgBundler.buildDMG(MacDmgBundler.java:398)

	at com.oracle.tools.packager.mac.MacDmgBundler.bundle(MacDmgBundler.java:92)

	at com.oracle.tools.packager.mac.MacDmgBundler.execute(MacDmgBundler.java:549)

	at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:352)

	at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:319)

	at com.sun.javafx.tools.packager.Main.main(Main.java:476)

  Config files are saved to /var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/fxbundler7345655397073451063/macosx. Use them to customize package.

Exception in thread "main" com.sun.javafx.tools.packager.PackagerException: Error: Bundler "DMG Installer" (dmg) failed to produce a bundle.

	at com.sun.javafx.tools.packager.PackagerLib.generateNativeBundles(PackagerLib.java:354)

	at com.sun.javafx.tools.packager.PackagerLib.generateDeploymentPackages(PackagerLib.java:319)

	at com.sun.javafx.tools.packager.Main.main(Main.java:476)



> Task :packageApplicationDmg FAILED
```
</p>
</details>

But no idea how your change could cause that. I've relaunched.

**Comment by joshmoore** [comment]
(Failed again)

**Comment by jburel** [comment]
```java.lang.NumberFormatException: Illegal embedded sign character

	at java.math.BigInteger.<init>(BigInteger.java:428)

	at java.math.BigInteger.<init>(BigInteger.java:606)

	at com.oracle.tools.packager.mac.MacAppBundler.validCFBundleVersion(MacAppBundler.java:330)

	at com.oracle.tools.packager.mac.MacAppBundler.lambda$static$199(MacAppBundler.java:167)

	at com.oracle.tools.packager.BundlerParamInfo.fetchFrom(BundlerParamInfo.java:132)

	at com.oracle.tools.packager.mac.MacAppBundler.doValidate(MacAppBundler.java:396)
``` This is expected when the version is ``version-SNAPSHOT/mXX``

**Comment by jburel** [comment]
It is green now

**Pull request merged**
