### PR TITLE
Fiji: import image not saved on disk: windows

### PR DESCRIPTION
**Pull request by jburel**
To test:
* Open an image stored in OMERO
* Crop the image
* Import the image. Do not save it locally first
* Check that it works on Windows and Mac
cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
https://github.com/ome/omero-insight/issues/206

**Comment by pwalczysko** [comment]
Unfortunately, I can see no change in behaviour with the artifacts from https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-build/ - everything is exactly the same as before on Win 10 VB.

**Comment by dominikl** [comment]
Could it be possible that Windows doesn't allow any longer to create a directory with a `.something` "file extension"?

**Comment by dominikl** [comment]
Works for me 👍  Tested "crop" workflow with the FRAP dataset on merge-ci. Hopefully @pwalczysko can confirm that too.

**Comment by pwalczysko** [comment]
Tested on :

   - Win 10 Virtual Box
   - Win 7 laptop
   - Mac OS Mojave
 
Tested workflows:

  - Crop with selection of an existing D
  - Crop with New From Folder
  - Crop with creation of new P/D
  - Line plot image
  - "Add images from current window"
  - "Add images from all open windows"
 
All works as expected. Ready to merge fmpov

**Comment by jburel** [comment]
Thanks for testing. @dominikl @pwalczysko

**Pull request merged**
