### PR TITLE
class path fix for imagej plugin

### PR DESCRIPTION
**Pull request by rgozim**
Fixes a class path for the imagej plugin distribution.

- test with imagej

See https://github.com/ome/omero-insight/issues/64

### CODE REVIEW

**Comment by jburel** [comment]
* Testing the plugin with Fiji and ImageJ  both work as expected
* Run ``gradle run``, it works as expected

cc @pwalczysko

**Comment by jburel** [comment]
We should do a release on insight with this PR included

**Comment by pwalczysko** [comment]
Test

   - Mac ImageJ 1.52k with java 1.8.0_172 (downloaded yesterday) - pass
   - Mac Fiji - pass
   - Win7 ImageJ 1.47 - fail, connects, but not able to open any image - will retest, maybe with newer imageJ, had to restart the win7 machine as all was slow
   - Win7 Fiji - had an outdated Fiji on Win7, need to download a new one

**Comment by pwalczysko** [comment]
Problem:

  - donwloaded a fresh Fiji from the website, started it and run the updater
  - connected to OMERO using the plugin from this PR - the splashscreen came up okay, but after I have entered the creds, I got

```
[Wed Aug 21 12:21:12 BST 2019] [INFO] [] Reading available sites from https://imagej.net/
[Wed Aug 21 12:23:10 BST 2019] [ERROR] [] null
java.lang.NoSuchMethodException: Could not find method com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
There was a problem with the class com.sun.jna.Native which can be found here:
/C:/Users/petr/DOWNLO~1/FIJI-W~1/Fiji.app/jars/jna-4.5.2.jar
/C:/Users/petr/DOWNLO~1/FIJI-W~1/Fiji.app/plugins/OMERO.imagej-5.5.4-SNAPSHOT/lib/jna-5.3.0.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.win32.Version.<clinit>(Version.java:37)
	at org.openmicroscopy.shoola.env.data.model.appdata.WindowsApplicationDataExtractor.extractAppData(WindowsApplicationDataExtractor.java:236)
	at org.openmicroscopy.shoola.env.data.model.ApplicationData.<init>(ApplicationData.java:112)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.readExternalApplications(TreeViewerFactory.java:477)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:427)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:193)
	at org.openmicroscopy.shoola.agents.treeviewer.TreeViewerAgent.activate(TreeViewerAgent.java:661)
	at org.openmicroscopy.shoola.env.Container.activateAgents(Container.java:327)
	at org.openmicroscopy.shoola.env.Container.startService(Container.java:360)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:197)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:488)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:412)
	at org.openmicroscopy.shoola.MainIJPlugin.run(MainIJPlugin.java:272)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

	at com.sun.jna.platform.win32.Version.<clinit>(Version.java:37)
	at org.openmicroscopy.shoola.env.data.model.appdata.WindowsApplicationDataExtractor.extractAppData(WindowsApplicationDataExtractor.java:236)
	at org.openmicroscopy.shoola.env.data.model.ApplicationData.<init>(ApplicationData.java:112)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.readExternalApplications(TreeViewerFactory.java:477)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:427)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:193)
	at org.openmicroscopy.shoola.agents.treeviewer.TreeViewerAgent.activate(TreeViewerAgent.java:661)
	at org.openmicroscopy.shoola.env.Container.activateAgents(Container.java:327)
	at org.openmicroscopy.shoola.env.Container.startService(Container.java:360)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:197)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:488)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:412)
	at org.openmicroscopy.shoola.MainIJPlugin.run(MainIJPlugin.java:272)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by rgozim** [comment]
Looks like that bug existed before this PR. I'll open a new one to address it.

**Comment by pwalczysko** [comment]
@rgozim the retest of the problem https://github.com/ome/omero-insight/pull/65#issuecomment-523416136 with the same Fiji on win7 but now with a release 5.5.3 insight-ij plugin shows that the error was there already before this PR (i.e. this error is present already in the released version, we did not catch it, as it does not show on Mac (or shows only in fresh Fiji). cc @jburel

**Comment by pwalczysko** [comment]
@jburel @rgozim it seems now that https://github.com/ome/omero-insight/pull/65#issuecomment-523416136 is a Win&freshFiji only problem. Fresh Fiji on Mac works fine with 5.5.3 release plugin.

**Comment by jburel** [comment]
@pwalczysko yes it is a Windows only problem

**Comment by jburel** [comment]
retested this on windows as part of the Fiji investigation problem. Everything works as expected
The problem reported by @pwalczysko will be fixed in another PR.

**Pull request merged**
