### PR TITLE
build pkg

### PR DESCRIPTION
**Pull request by jburel**
Distribute the PKG
https://github.com/jburel/omero-insight/releases/tag/v5.5.17

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
I am happy with the OMERO.insight pkg. 
Nevertheless, the OMERO.imprater pkg seems to be installing itself on a weird place ? I simply cannot find it after successful install, neither in Applications nor via Spotlight search.

**Comment by jburel** [comment]
I will leave it for now, and do further  check

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#9](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/9/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/9/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .github/workflows/gradle.yml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#9](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/9/). See the [console output](https://snoopycrimecop-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/9/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - .github/workflows/gradle.yml

--conflicts

**Pull request closed without merging**
