### PR TITLE
Add support for third party jars

### PR DESCRIPTION
**Pull request by jburel**
Add support for https://github.com/ome/omero-insight/issues/59

cc @sbesson 

--exclude

### CODE REVIEW

**Comment by sbesson** [comment]
Having briefly looked at this, this PR currently addresses the the ability to build a custom OMERO.insight with third-party JARs. We briefly discussed with @jburel whether an extension point that does not require a complete build of OMERO.insight is feasible. He will carry out further tests and update this PR.

**Comment by sbesson** [comment]
For testing the 3i Slidebook JAR addition, I used the Slidebook file under `curated/slidebook/alexia/utrophinGFP_sih_e1_time1.sld` (262M).

**Comment by jburel** [comment]
@sbesson are you sure the image is valid?
I have the following error
```
java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at loci.formats.in.SlidebookReader.initFile(SlidebookReader.java:1179)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
```

**Comment by jburel** [comment]
I used ``curated/slidebook/steve/Rho2.sld`` but that file does not seem to need the jar in the ClassPath.

**Comment by sbesson** [comment]
> java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
> 	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
> 	at java.util.ArrayList.get(ArrayList.java:433)
> 	at loci.formats.in.SlidebookReader.initFile(SlidebookReader.java:1179)
> 	at loci.formats.FormatReader.setId(FormatReader.java:1389)

From the stack trace, the legacy Slidebook reader is picked so the exception is expected. Testing the 3i slidebook reader from the command-line tools works:

```
build@457d12262828:~$ /bio-formats-build/bioformats/tools/showinf -nopix /data/alexia/utrophinGFP_sih_e1_time1.sld 
Checking file format [Olympus Slidebook]
Initializing reader
SlidebookReader initializing /data/alexia/utrophinGFP_sih_e1_time1.sld
Finding offsets to pixel data
Determining dimensions
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at loci.formats.in.SlidebookReader.initFile(SlidebookReader.java:1179)
	at loci.formats.FormatReader.setId(FormatReader.java:1389)
	at loci.formats.ImageReader.setId(ImageReader.java:843)
	at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
	at loci.formats.tools.ImageInfo.testRead(ImageInfo.java:1035)
	at loci.formats.tools.ImageInfo.main(ImageInfo.java:1121)
build@457d12262828:~$ wget https://sites.imagej.net/SlideBook/jars/bio-formats/SlideBook6Reader.jar-20190125132114 && mv SlideBook6Reader.jar-20190125132114 SlideBook6Reader.jar
--2020-04-07 09:01:46--  https://sites.imagej.net/SlideBook/jars/bio-formats/SlideBook6Reader.jar-20190125132114
Resolving sites.imagej.net (sites.imagej.net)... 144.92.48.177
Connecting to sites.imagej.net (sites.imagej.net)|144.92.48.177|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2406016 (2.3M)
Saving to: ‘SlideBook6Reader.jar-20190125132114’

SlideBook6Reader.jar-20190125132114    100%[=========================================================================>]   2.29M  1.75MB/s    in 1.3s    

2020-04-07 09:01:49 (1.75 MB/s) - ‘SlideBook6Reader.jar-20190125132114’ saved [2406016/2406016]

build@457d12262828:~$ BF_CP=./SlideBook6Reader.jar /bio-formats-build/bioformats/tools/showinf -nopix /data/alexia/utrophinGFP_sih_e1_time1.sld
Checking file format [SlideBook 6 SLD (native)]
Initializing reader
SlideBook6Reader initializing /data/alexia/utrophinGFP_sih_e1_time1.sld
Initialization took 0.129s

Reading core metadata
filename = /data/alexia/utrophinGFP_sih_e1_time1.sld
Series count = 1
Series #0 :
	Image count = 520
	RGB = false (1) 
	Interleaved = true
	Indexed = false (true color)
	Width = 512
	Height = 512
	SizeZ = 260
	SizeT = 1
	SizeC = 2
	Tile size = 512 x 512
	Thumbnail size = 128 x 128
	Endianness = intel (little)
	Dimension order = XYCZT (uncertain)
	Pixel type = uint16
	Valid bits per pixel = 16
	Metadata complete = false
	Thumbnail series = false
	-----
	Plane #0 <=> Z 0, C 0, T 0
	Plane #258 <=> Z 129, C 0, T 0
	Plane #259 <=> Z 129, C 1, T 0
	Plane #260 <=> Z 130, C 0, T 0
	Plane #261 <=> Z 130, C 1, T 0
	Plane #262 <=> Z 131, C 0, T 0
	Plane #519 <=> Z 259, C 1, T 0


Reading global metadata

Reading metadata
```

**Comment by jburel** [comment]
Thanks so the order is not correct in the classpath.

**Comment by jburel** [comment]
The code client side is correct i.e. the jar was getting picked up.
The error was "server" side since I forgot to upload the jar

**Pull request closed without merging**
