### PR TITLE
use toURI method to handle

### PR DESCRIPTION
**Pull request by jburel**
This should fix issue with file path.
see https://www.openmicroscopy.org/qa2/qa/feedback/30780/ and https://github.com/ome/omero-insight/issues/237
cc @dominikl

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#1011](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/1011/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/1011/consoleText) for more details.
Possible conflicts:
  - PR #216 jburel 'path error'
    - src/main/java/org/openmicroscopy/shoola/util/ui/filechooser/GenericFileChooser.java

--conflicts

**Comment by dominikl** [comment]
Ah interesting, that might fix a few other similar issues too. I'll review later.

**Comment by dominikl** [comment]
Tested with a build from the PR branch. Looks good, doesn't break anything. I don't know how to replicate the issue though.

**Comment by jburel** [comment]
Did you try on Windows 10? since this is the OS which seems to trigger the problem
cc @pwalczysko

**Comment by dominikl** [comment]
Yes, Windows 10 and imported from local as well as network share, both works (with and without the PR).

**Comment by dominikl** [comment]
This PR now also Fixes [#111](https://github.com/ome/omero-insight/issues/111) .

To replicate that error: Open import dialog. In the drop down select "This PC". Insight crashes with InvalidPathException. Has to be tested on Windows 10.

Test: Check that Insight doesn't crash with this PR.

**Comment by pwalczysko** [comment]
How to start an insight https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-build/ on windows ?

**Comment by pwalczysko** [comment]
I can confirm the crash with release insight when I select in importer the "Computer" folder on Windows (maxquant).
The crash throws

```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.nio.file.InvalidPathException: Illegal char <:> at index 52: C:\Users\pwalczysko\AppData\Local\OMERO.insight\app\::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
...
```

**Comment by pwalczysko** [comment]
Import seems to work normally on Windows with this PR. 

I am tempted to say that is all we can do in terms of testing here, as the original error https://github.com/ome/omero-insight/issues/237 workflow is not described. It definitely does not just happen because on Windows, the app works more or less normally.

cc @jburel ?

**Comment by jburel** [comment]
See also https://www.openmicroscopy.org/qa2/qa/feedback/30868/

**Comment by pwalczysko** [comment]
> @pwalczysko any objection if I merge this PR, I would like to include it in a point release

Good to merge fmpov

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
