### PR TITLE
Help

### PR DESCRIPTION
**Pull request by jburel**
Update version in the help

The value should match the value displayed on the login screen

cc @mtbc

### CODE REVIEW

**Comment by mtbc** [comment]
This fails with `gradle run` but maybe that's expected? There's probably some other gradle thing I'm meant to use? I tried `gradle distTar` but can't find what it made, apparently nothing.

**Comment by jburel** [comment]
What do you mean by fail? Did it show "unknow"? if it is the case, that is expected

**Comment by mtbc** [comment]
It did.

**Comment by mtbc** [comment]
I was hoping that I could do some other kind of build and get an actual number there? But maybe not?

**Comment by jburel** [comment]
I did a ``gradle build`` and in that case the version does not seem to be picked. I will need to review it

**Comment by jburel** [comment]
To test 
 * run ``gradle build``
 * unzip the ``build/distributions/OMERO.insight-5.5.3-SNAPSHOT.zip``
 * run ``build/distributions/OMERO.insight-5.5.3-SNAPSHOT/bin/omero-insight``
 * log in and go to help

**Pull request merged**
