### PR TITLE
MDE enabled in the standard configuration of importer

### PR DESCRIPTION
**Pull request by sukunis**
For easier use of the OMERO.mde also for users who download the OMERO.insight as an `exe` . Default location for a `mdeConfiguration` file is the local user omero directory.

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#816](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/816/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/816/consoleText) for more details.
Possible conflicts:
  - PR #227 dominikl 'Escape ice special characters for login'
    - src/config/container.xml
    - src/config/containerImporter.xml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#816](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/816/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/816/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/config/container.xml
    - src/config/containerImporter.xml

--conflicts

**Comment by joshmoore** [comment]
Just to add a little context, with the mde paper in preparation, it would be good to make accessing the extension easier. If anyone has issues with its stability or presence in the UI, let's try to find a solution that doesn't require users (or system administrators) to hand edit an XML file.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#818](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/818/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/818/consoleText) for more details.
Possible conflicts:
  - PR #227 dominikl 'Escape ice special characters for login'
    - src/config/container.xml
    - src/config/containerImporter.xml

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#818](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/818/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/818/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/config/container.xml
    - src/config/containerImporter.xml

--conflicts

**Comment by jburel** [comment]
Tested with build https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-build/822/
MDE is turned on by default, no impact on the import functionality
Imported using both ``non mde`` and ``mde`` option

**Comment by sbesson** [comment]
@sukunis thanks for all your work on this project. We are in the process of rolling out a Contributor License Agreement for all external contributions to the OME repositories. Instructions are available [here](https://ome-contributing.readthedocs.io/en/latest/cla.html). Could you fill out the form and send it back to us?

**Pull request merged**
