### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by jburel**
this PR migrates the documentation associated to OMERO.insight next to the code.
see https://jburel-omero-insight.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by dominikl** [comment]
I think `omero-insight-architecture-agents.png` is the wrong image (but with the correct name). See https://jburel-omero-insight.readthedocs.io/en/latest/_images/omero-insight-architecture-agents.png vs https://docs.openmicroscopy.org/omero/5.6.3/_images/omero-insight-architecture-agents.png .

**Comment by dominikl** [comment]
Apart from that looks good 👍 And the order of the bullet points in the rtd documentation makes even more sense than on the original docs.

**Comment by jburel** [comment]
@dominikl The problem should be fixed now

**Comment by dominikl** [comment]
Thanks @jburel , looks good now 👍

**Pull request merged**
