### PR TITLE
Add config to jar

### PR DESCRIPTION
**Pull request by jburel**
Second phase
This PR includes config folder in the fat jar. This should make it easier for users to install the plugin
if you have previously installed omero.imagej in the plugins directory of ImageJ/Fiji, you first need to delete it.
To test with Fiji and ImageJ
 * If you build locally, you will under ``build/libs``, the ``omero_ij*.jar``. 
 * If you retrieve it from merge-ci, unzip ``imagej*.zip`` and retrieve the jar.  (When we tag, the ``zip`` will not be pushed, the ``jar`` will.
 * Place the omero_ij jar into the plugins directory.
 * Check that you can connect and view images etc.
 * Disconnect
 * ImageJ only, Check that there is no file ``logFileName_IS_UNDEFINED`` created in the folder containing ImageJ

cc @pwalczysko

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good. Tested with latest Fiji on Windows 10. Only copied the jar into the plugins folder.
Got a `[WARN] UPGRADE AVAILABLE:Please upgrade to 5.5.1.` but apart from that worked fine.

**Comment by dominikl** [comment]
The config folder is still part of the zip, too. That might be a bit confusing for the users.

**Comment by dominikl** [comment]
ImageJ is ok too, didn't see any `logFileName_IS_UNDEFINED` file.

**Comment by jburel** [comment]
@dominikl the zip should no longer be uploaded. 
I will remove the config from the zip in case some uses it

**Comment by jburel** [comment]
@dominikl done

**Comment by dominikl** [comment]
Tested with a local build because of the travis error. No config directory included any longer, and plugin still works as expected. Good to merge from my point of view 👍

**Comment by jburel** [comment]
Travis is green again.
Merging so that @dominikl can fix the conflicts in his PR

**Pull request merged**
