### PR TITLE
handle null value

### PR DESCRIPTION
**Pull request by jburel**
handle null value
This was noticed on some images locally. The value returned was ``null``, this implies that the imported was constantly changing.

### CODE REVIEW

**Comment by joshmoore** [comment]
@jburel : if it could change at any moment, you'd probably be better of capturing the results once and then reusing it:

```
Something i = i.getInserted();
if (i != null) {
    i.somethingElse();
}
```

**Comment by jburel** [comment]
What is intriguing is why 
``
if (event == null || !event.isLoaded() || event.getTime() == null) return null
``
is true where event is ``getCreationEvent`` for an image

**Comment by jburel** [comment]
@joshmoore happy with the last commit?

**Comment by joshmoore** [comment]
WFM.

**Pull request merged**
