### PR TITLE
Importer

### PR DESCRIPTION
**Pull request by rgozim**
Adds option for building an installer for OMERO.importer.

`gradle packageImporterApplication[dmg,pkg,exe,msi]`

Requires:
https://github.com/ome/omero-javapackager-plugin/pull/7

### CODE REVIEW

**Comment by jburel** [comment]
This is never going to pass travis due to the usage of snapshot

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#68](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-insight-push/68/). See the [console output](https://web-proxy.openmicroscopy.org/west-ci/job/OMERO-insight-push/68/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - buildSrc/build.gradle

--conflicts

**Comment by jburel** [comment]
```
A problem was found with the configuration of task ':packageImporterApplicationDmg'.
> Directory '/Users/jmarie/Documents/git-repo/omero-insight/build/install/OMERO.importer' specified for property 'argumentProviders.$1.srcDir' does not exist.
```

**Comment by jburel** [comment]
```gradle packageApplicationPkg``` works

**Comment by jburel** [comment]
--exclude 
(testing why it is in the build)

**Comment by jburel** [comment]
Exe, dmg are correctly created now
Merging

**Pull request merged**
