### PR TITLE
Build windows executable via travis

### PR DESCRIPTION
**Pull request by jburel**
This allows to build the windows executable in travis
We can now build both .exe and msi via travis

Note that installing Wix directly with chocolatey does not work (dotnet3.5 failure)

Edit: test failure on windows is fixed and re-activated

cc @pwalczysko @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
That's great 👍 I'll stop trying on Azure then.

**Comment by jburel** [comment]
Deployment of .exe on tagging testing via https://github.com/jburel/omero-insight/releases/tag/v5.5.10

**Comment by dominikl** [comment]
Tested the exe files on Windows 10 VM, works fine 👍

**Comment by jburel** [comment]
insight.msi can be tested https://github.com/jburel/omero-insight/releases/tag/v5.5.11
msi was built via travis. 
msi will only be built when a tag is pushed. ``SNAPSHOT`` in the version is not supported

**Comment by dominikl** [comment]
Looks good. Both exe and msi install fine. I just can't connect to demo server at the moment, because all UoD connections seem to be very, very slow and intermittent. 

One issue with the windows installers on windows 10 in general is, although not related to this PR:
Screen Shot 2020-03-19 at 11 28 39

Then you have to click on "More info" in order to be able to proceed:
Screen Shot 2020-03-19 at 11 28 51

Well, at least that's as intuitive as one would expect from Windows 10 anyway...

**Comment by jburel** [comment]
We will probably need to add a publisher etc.

**Comment by dominikl** [comment]
Managed to connect to workshop server by now too 👍

**Comment by jburel** [comment]
I have included the creation of importer artifacts for now. I have created a new topic on https://forum.image.sc/t/omero-desktop-client-omero-insight/35234

**Comment by jburel** [comment]
@dominikl cf publisher https://github.com/ome/omero-insight/issues/82

**Comment by dominikl** [comment]
Good to merge from my point of view. If you want to run a 'release' again, I can test it again, but should not be necessary actually.

**Comment by jburel** [comment]
Travis timed out for some reasons.
I will do another "release" against my repo so we can check the vendor flag

**Comment by jburel** [comment]
@dominikl travis is green so the test is passing :-)

**Comment by jburel** [comment]
Merging Thanks @dominikl for the testing

**Pull request merged**
