### PR TITLE
Add feature MDE - metadata editor for OMERO.importer

### PR DESCRIPTION
**Pull request by sukunis**
beta-version

### CODE REVIEW

**Comment by pwalczysko** [comment]
@sukunis  Hello, this is great and thank you

I was wondering if you could point me to a wokflow with concrete fields filled in and a pointer as to where the intput will be located. I found https://www.ibios.uni-osnabrueck.de/index.php?cat=Service&file=OMEROImporter_v5.2_HandsOn.pdf but in the step where the metadata are added are not detailed enough. Thank you

**Comment by sukunis** [comment]
@pwalczysko 
I have add more detailed description to the Readme of my branch. An example configuration file is stored in the repository. You have to put it under <user>/omero/ . If no configuration file is available, default OME objects are loaded. If you add some annotations in the MDE, after import they should be available under key-value-pairs.

**Comment by sukunis** [comment]
sorry: the path is /&lt;user &gt;/omero ( where the logfiles directory is located)

**Comment by pwalczysko** [comment]
Thank you @sukunis 

So I have the .xml file now and understood how to create Key-Value pairs using your app.

Screen Shot 2019-08-27 at 15 58 44

I also thought that I can apply the settings on a whole folder in one go. Is that true ? At the moment, I am getting no Key-Value pairs if I select a whole subfolder in local hierarchy in your app and apply the new settings to it (see screenshot below, I do have success though if I select just one single image, see screenshot above)

Screen Shot 2019-08-27 at 16 09 30

Is there a possibility to add the metadata to several images in one click ?

**Comment by pwalczysko** [comment]
<details>
 <summary>Some details to think about in this PR</summary>

Not having the .xml file in your <home>/omero folder makes problems
Error on start of insight complaining of missing xml
2x crashed insight with an NPE (different workflows, hard to establish exact sequence of clicks),    NPE see at [1]
Merge-ci server (out testing OMERO.server) was not capable of importing anymore after several imports with this insight


[1]
```
java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.deselectNodeAction(MetaDataDialog.java:580)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.valueChanged(MetaDataDialog.java:893)
    at javax.swing.JTree.fireValueChanged(JTree.java:2934)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
    at javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:577)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:758)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:297)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:212)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.util.EditorFileBrowser.createNodes(EditorFileBrowser.java:73)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.refreshFileView(MetaDataDialog.java:733)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.refreshMetaFileView(ImporterUI.java:508)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:432)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.propertyChange(ImporterControl.java:376)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8434)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1722)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at java.awt.Component.firePropertyChange(Component.java:8454)
    at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6539)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6304)
    at java.awt.Container.processEvent(Container.java:2239)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2297)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
    at java.awt.Container.dispatchEventImpl(Container.java:2283)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
    at java.awt.EventQueue$4.run(EventQueue.java:733)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.deselectNodeAction(MetaDataDialog.java:580)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.valueChanged(MetaDataDialog.java:893)
    at javax.swing.JTree.fireValueChanged(JTree.java:2934)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
    at javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:577)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:758)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:297)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:212)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.util.EditorFileBrowser.createNodes(EditorFileBrowser.java:73)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.refreshFileView(MetaDataDialog.java:733)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.refreshMetaFileView(ImporterUI.java:508)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:432)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.propertyChange(ImporterControl.java:376)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8434)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1722)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at java.awt.Component.firePropertyChange(Component.java:8454)
    at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6539)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6304)
    at java.awt.Container.processEvent(Container.java:2239)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2297)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
    at java.awt.Container.dispatchEventImpl(Container.java:2283)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
    at java.awt.EventQueue$4.run(EventQueue.java:733)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0"

    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:189)
    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:289)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
    at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
    at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

java.lang.Exception: Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.deselectNodeAction(MetaDataDialog.java:580)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.valueChanged(MetaDataDialog.java:893)
    at javax.swing.JTree.fireValueChanged(JTree.java:2934)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
    at javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:577)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:758)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:297)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:212)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.util.EditorFileBrowser.createNodes(EditorFileBrowser.java:73)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.refreshFileView(MetaDataDialog.java:733)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.refreshMetaFileView(ImporterUI.java:508)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:432)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.propertyChange(ImporterControl.java:376)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8434)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1722)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at java.awt.Component.firePropertyChange(Component.java:8454)
    at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6539)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6304)
    at java.awt.Container.processEvent(Container.java:2239)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2297)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
    at java.awt.Container.dispatchEventImpl(Container.java:2283)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
    at java.awt.EventQueue$4.run(EventQueue.java:733)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Abnormal termination due to an uncaught exception.
java.lang.NullPointerException
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.deselectNodeAction(MetaDataDialog.java:580)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.valueChanged(MetaDataDialog.java:893)
    at javax.swing.JTree.fireValueChanged(JTree.java:2934)
    at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3398)
    at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
    at javax.swing.tree.DefaultTreeSelectionModel.clearSelection(DefaultTreeSelectionModel.java:577)
    at javax.swing.tree.VariableHeightLayoutCache.rebuild(VariableHeightLayoutCache.java:758)
    at javax.swing.tree.VariableHeightLayoutCache.treeStructureChanged(VariableHeightLayoutCache.java:644)
    at javax.swing.plaf.basic.BasicTreeUI$Handler.treeStructureChanged(BasicTreeUI.java:3917)
    at javax.swing.tree.DefaultTreeModel.fireTreeStructureChanged(DefaultTreeModel.java:580)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:297)
    at javax.swing.tree.DefaultTreeModel.reload(DefaultTreeModel.java:212)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.util.EditorFileBrowser.createNodes(EditorFileBrowser.java:73)
    at org.openmicroscopy.shoola.agents.fsimporter.mde.MetaDataDialog.refreshFileView(MetaDataDialog.java:733)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterUI.refreshMetaFileView(ImporterUI.java:508)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.handlePropertyChangedEvent(ImporterControl.java:432)
    at org.openmicroscopy.shoola.agents.fsimporter.view.ImporterControl.propertyChange(ImporterControl.java:376)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.awt.Component.firePropertyChange(Component.java:8434)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.ImportDialog.propertyChange(ImportDialog.java:1722)
    at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
    at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:303)
    at java.awt.Component.firePropertyChange(Component.java:8454)
    at javax.swing.JComponent.firePropertyChange(JComponent.java:4491)
    at org.openmicroscopy.shoola.agents.fsimporter.chooser.FileSelectionTable.actionPerformed(FileSelectionTable.java:698)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
    at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
    at java.awt.Component.processMouseEvent(Component.java:6539)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6304)
    at java.awt.Container.processEvent(Container.java:2239)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2297)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
    at java.awt.Container.dispatchEventImpl(Container.java:2283)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
    at java.awt.EventQueue$4.run(EventQueue.java:733)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0"

    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.showErrorDialog(UserNotifierImpl.java:189)
    at org.openmicroscopy.shoola.env.ui.UserNotifierImpl.notifyError(UserNotifierImpl.java:289)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.doTermination(AbnormalExitHandler.java:147)
    at org.openmicroscopy.shoola.env.AbnormalExitHandler.terminate(AbnormalExitHandler.java:85)
    at org.openmicroscopy.shoola.env.RootThreadGroup.uncaughtException(RootThreadGroup.java:69)
    at java.awt.EventDispatchThread.processException(EventDispatchThread.java:227)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:219)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```



</details>

**Comment by sukunis** [comment]
Regarding the configuration file: there shouldn't be any problems not having this file ( i couldn't reproduce any problems locally). In that case only standard OME objects will be loaded as UNIVERSAL. You only need the configuration file to customize your MDE forms (predefined values for objects, new objects). The ERROR output is missleading, i think.

**Comment by sukunis** [comment]
I fixed some bugs regarding inherit input from parent directory and save MapAnnotation. Also catch the exception produced above.

**Comment by jburel** [comment]
@sukunis Thanks for opening a PR, few general comments
* Do you have that code already used by local users?
* insight uses a logger I/F. I noticed some direct usage of slf4j in some places. It is preferable to use the logger (wrapper around slf4j by default) available via the registry. 
* debug: we could add a new logger implementation to print out in the console (similar to Plugin Logger) to avoid the print out in many classes.
* agents classes should not be visible by classes in the ``env`` directory
* content of the readme should not be removed. We need those instructions for general usage of insight
 * The ``mde`` extension should be configurable similar to offline import. I have already done some changes to that effect. https://github.com/jburel/omero-insight/tree/feat_MDE. Happy to open a PR if you are ready to accept code.
* New files need to have a copyright. See https://docs.openmicroscopy.org/contributing/code-contributions.html for more info. Depending on the chosen option, we might have to re-architecture the new code. The easiest will be to "grant" ome the code and use the header in the existing files.
* People have been thinking about "metadata" addition in the web environment. One existing app that might be of interest https://github.com/sorgerlab/OMERO.forms. The code has not been worked on for a while but it gives an idea of what people are thinking.

**Comment by sukunis** [comment]
@jburel 

>     * Do you have that code already used by local users?
First at all, this is only a beta-version ( a redesign of an existing editor). Local we use the former version, but there are many changes after this redesign. Another point is, that I still develop against the 5.4.10 version. Any changes will be merged to the 5.5 version and I also make a quick check against the demo server in Dundee. I hope we can switch our server to the 5.5 version in the next two weeks.
> 
>     * insight uses a logger I/F. I noticed some direct usage of slf4j in some places. It is preferable to use the logger (wrapper around slf4j by default) available via the registry.
> 
in progress.
>     * debug: we could add a new logger implementation to print out in the console (similar to Plugin Logger) to avoid the print out in many classes.
> 
I will clean up the debug outputs. 

>     * agents classes should not be visible by classes in the `env` directory
Done
> 
>     * content of the readme should not be removed. We need those instructions for general usage of insight
Does it make more sense to have an additional readme in the mde directory?
> 
>     * The `mde` extension should be configurable similar to offline import. I have already done some changes to that effect. https://github.com/jburel/omero-insight/tree/feat_MDE. Happy to open a PR if you are ready to accept code.
> 
Great, i'm looking forward to your PR!

>     * New files need to have a copyright. See https://docs.openmicroscopy.org/contributing/code-contributions.html for more info. Depending on the chosen option, we might have to re-architecture the new code. The easiest will be to "grant" ome the code and use the header in the existing files.
> 
In progress.

>     * People have been thinking about "metadata" addition in the web environment. One existing app that might be of interest https://github.com/sorgerlab/OMERO.forms. The code has not been worked on for a while but it gives an idea of what people are thinking.

I had already started with the development of an OMERO web plugin in 2017, but for time reasons not pursued further ( if i remember correctly, I was talking about it last year in Dundee). 
Another future developments could are: 

- mdeConfiguration.xml is assign to groups on server, so that the mde objects are changing dependent on the destination group i will import for. Which implies a mde configuration dialog in OMERO.web.
- RDF parser to add objects from different ontologies
- use MDE as generator for bulk import yml files for automatic OMERO.cli imports

**Comment by jburel** [comment]
* For the readme. We should probably add a file and with a link to that file in the README
and indicate how to turn MDE on. I would take care of that in my branch if it helps

**Comment by jburel** [comment]
* PR opened against your branch for review
* Adjustment to README made in the PR

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#85](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/85/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/85/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/main/java/org/openmicroscopy/shoola/env/LookupNames.java

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#97](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/97/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/97/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - src/main/java/org/openmicroscopy/shoola/env/LookupNames.java

--conflicts

**Comment by jburel** [comment]
@sukunis I have replaced the ``MonitorAndDebug`` class  by ``ConsoleLoggerImpl`` class. This can also be configured in ``container.xml`` or ``containerImporter.xml`` by setting ``<entry name="/services/LOG/output/console" type="boolean">false</entry>`` to ``true``

**Comment by jburel** [comment]
Thanks @sukunis. Merging so it is included in the coming 5.6 version
so you won't have to maintain a separate branch

**Pull request merged**
