### PR TITLE
QA 29728: fix 

### PR DESCRIPTION
**Pull request by sukunis**
disable load filter button if no template file is selected

### CODE REVIEW

**Comment by jburel** [comment]
Changes look good and build is green

**Review by jburel — APPROVED** [review]

**Comment by jburel** [comment]
@sukunis do you need a new release with this fix or do you have more changes to push?

**Comment by sukunis** [comment]
More corrections and functions are coming.

**Comment by jburel** [comment]
Thanks merging this PR and waiting for more bug fixes

**Pull request merged**
