### PR TITLE
Gradle7 fix

### PR DESCRIPTION
**Pull request by jburel**
This PR tests the build in GHA with Gradle 6.8.3
The changes should work with Gradle 7. 
The failure happened when running ``gradle wrapper --gradle-version=6.8.3``
cc @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
Looks good to me, certainly the builds are passing now 👍

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-build/747/ failed!!! grrrr

**Comment by jburel** [comment]
on our CI with Gradle 5.2.1
```
org.gradle.api.distribution.Distribution#getDistributionBaseName(). Please check if the declared type is correct and if the method exists.
 @ line 112, column 13.
               importer.getDistributionBaseName().set(DISTRIBUTION_NAME_IMPORTER)
               ^

/home/omero/workspace/OMERO-insight-build/buildSrc/src/main/groovy/org/openmicroscopy/DistributePlugin.groovy: 133: [Static type checking] - Cannot find matching method org.gradle.api.distribution.Distribution#getDistributionBaseName(). Please check if the declared type is correct and if the method exists.
 @ line 133, column 13.
               imageJ.getDistributionBaseName().set(DISTRIBUTION_NAME_IMAGEJ)
               ^
```
This is getting painful.

**Comment by sbesson** [comment]
https://docs.gradle.org/current/javadoc/org/gradle/api/distribution/Distribution.html#getDistributionBaseName--

```
Since:
    6.0 
```

**Comment by jburel** [comment]
yep!

**Comment by sbesson** [comment]
NB: unlike `omero-build` where the consequences might need to be reviewed, I assume it is easier and less impactful to move to Gradle 6 as the minimum version on a downstream component like OMERO.insight.

This would still force us to upgrade our Jenkins hosted CI to Gradle 6+ but this is something where we want to go anyways.

**Comment by jburel** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-build/748/ is back to green
So with b94d23e88e844b60caddbcc41a9b9eed8ce2b4c5, GHA and merge-CI are green

**Comment by dominikl** [comment]
Looks ok to me, and builds are green 👍

**Pull request merged**
