### PR TITLE
Added a fat jar distribution of imagej for fiji

### PR DESCRIPTION
**Pull request by rgozim**
Adds a fat jar distribution for FIJI

- run `gradle installFijiDist` to build the Fiji distribution
- test with fiji

### CODE REVIEW

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#138](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/138/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/138/consoleText) for more details.
Possible conflicts:
  - PR #65 rgozim 'class path fix for imagej plugin'
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#138](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/138/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/138/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#59](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/59/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/59/consoleText) for more details.
Possible conflicts:
  - PR #65 rgozim 'class path fix for imagej plugin'
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#59](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/59/). See the [console output](https://idr-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/59/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by pwalczysko** [comment]
built locally being on this branch using ``gradle build``.
Then unzipped and transferred to Win7 machine, into the freshly downloaded Fiji from yesterday.
Fiji started, connect to OMERO, splashscreen appeared. Put creds in, then:

```
[Thu Aug 22 11:45:25 BST 2019] [ERROR] [] null
java.lang.NoSuchMethodException: Could not find method com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
There was a problem with the class com.sun.jna.Native which can be found here:
/C:/Users/petr/DOWNLO~1/FIJI-W~1/Fiji.app/jars/jna-4.5.2.jar
/C:/Users/petr/DOWNLO~1/FIJI-W~1/Fiji.app/plugins/OMERO.fiji-5.5.4-SNAPSHOT/omero_fiji-5.5.4-SNAPSHOT-all.jar

WARNING: multiple locations found!
java.lang.NoSuchMethodError: com.sun.jna.Native.load(Ljava/lang/String;Ljava/lang/Class;Ljava/util/Map;)Lcom/sun/jna/Library;
	at com.sun.jna.platform.win32.Version.<clinit>(Version.java:37)
	at org.openmicroscopy.shoola.env.data.model.appdata.WindowsApplicationDataExtractor.extractAppData(WindowsApplicationDataExtractor.java:236)
	at org.openmicroscopy.shoola.env.data.model.ApplicationData.<init>(ApplicationData.java:112)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.readExternalApplications(TreeViewerFactory.java:477)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:427)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:193)
	at org.openmicroscopy.shoola.agents.treeviewer.TreeViewerAgent.activate(TreeViewerAgent.java:661)
	at org.openmicroscopy.shoola.env.Container.activateAgents(Container.java:327)
	at org.openmicroscopy.shoola.env.Container.startService(Container.java:360)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:197)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:488)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:412)
	at org.openmicroscopy.shoola.MainIJPlugin.run(MainIJPlugin.java:272)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)

	at com.sun.jna.platform.win32.Version.<clinit>(Version.java:37)
	at org.openmicroscopy.shoola.env.data.model.appdata.WindowsApplicationDataExtractor.extractAppData(WindowsApplicationDataExtractor.java:236)
	at org.openmicroscopy.shoola.env.data.model.ApplicationData.<init>(ApplicationData.java:112)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.readExternalApplications(TreeViewerFactory.java:477)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:427)
	at org.openmicroscopy.shoola.agents.treeviewer.view.TreeViewerFactory.getTreeViewer(TreeViewerFactory.java:193)
	at org.openmicroscopy.shoola.agents.treeviewer.TreeViewerAgent.activate(TreeViewerAgent.java:661)
	at org.openmicroscopy.shoola.env.Container.activateAgents(Container.java:327)
	at org.openmicroscopy.shoola.env.Container.startService(Container.java:360)
	at org.openmicroscopy.shoola.env.init.Initializer.notifyEnd(Initializer.java:197)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:488)
	at org.openmicroscopy.shoola.env.Container.startupInPluginMode(Container.java:412)
	at org.openmicroscopy.shoola.MainIJPlugin.run(MainIJPlugin.java:272)
	at ij.IJ.runUserPlugIn(IJ.java:230)
	at ij.IJ.runPlugIn(IJ.java:193)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#140](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/140/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/140/consoleText) for more details.
Possible conflicts:
  - PR #65 rgozim 'class path fix for imagej plugin'
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by rgozim** [comment]
Regardless of the above error discovered by @pwalczysko still persisting, this PR should probably still be included into insight.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#141](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/141/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/141/consoleText) for more details.
Possible conflicts:
  - PR #65 rgozim 'class path fix for imagej plugin'
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by jburel** [comment]
The fat jar did not solve the problem. We can revisit when we have a bit more time.
Also from feedback, it will be good to include the config dir in the jar since that was the source of several problems during training sessions.

**Comment by snoopycrimecop** [comment]
Conflicting PR. Removed from build [OMERO-insight-push#147](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/147/). See the [console output](https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-insight-push/147/consoleText) for more details.
Possible conflicts:
  - Upstream changes
    - buildSrc/src/main/groovy/org/openmicroscopy/InsightBasePlugin.groovy

--conflicts

**Comment by jburel** [comment]
Closing in favour of #72

**Pull request closed without merging**
