### PR TITLE
import wrong dataset

### PR DESCRIPTION
**Pull request by jburel**
This PR fixes https://github.com/ome/omero-insight/issues/94

The container is now created in the swing thread.
See the description in issue https://github.com/ome/omero-insight/issues/94 for testing instructions

cc @dominikl

### CODE REVIEW

**Comment by jburel** [comment]
@dominikl this PR was not included in today's build so I removed it from standup

**Comment by dominikl** [comment]
Looks good. Couldn't replicate the issue #94 with this PR. But I have to admit, although it's just a very short delay it feels a bit weird, like makes you question for a second if you actually clicked the button or not. Wonder if we could give some indication that something's happening. Wait cursor (but afaik we don't do that anywhere in Insight) or deactivate the "Create" button (in the `org.openmicroscopy.shoola.agents.util.ui.EditorDialog`)?

**Comment by joshmoore** [comment]
Going back to https://github.com/ome/omero-insight/issues/94#issuecomment-604546275, J-m said:

> here is no remote call on the swing thread

If that's the case, then what I meant in https://github.com/ome/omero-insight/issues/94#issuecomment-604511096 was that I'd strongly encourage us not to introduce a remote call on the Swing thread. There be dragons if we can at all avoid it.

**Comment by jburel** [comment]
I meant for that sequence. I think we might have one or 2 calls in the Swing thread but that will require confirmation. This is certainly not the norm

**Comment by jburel** [comment]
@dominikl if we are in the swing thread, we won't be able to give feedback
As mentioned on the issue, option 2 is preferable. i will close this PR and see how we can sort that out.

**Pull request closed without merging**
