### PR TITLE
Deprecate SERVER_5_4_8_OR_LATER.

### PR DESCRIPTION
**Pull request by mtbc**
Removes from Insight the special thumbnail handling for OMERO.server <5.4.8.

### CODE REVIEW

**Comment by dominikl** [comment]
I'm not really sure about this. Isn't `5.5.0` supposed to be backwards compatible with `5.4.x` ?

**Comment by mtbc** [comment]
Oh, is it? Sorry, I didn't realize, in which case, yes, best to close this.

**Comment by dominikl** [comment]
I'm not sure... just wondering because we now have the all the 'skip versioncheck' flags. @jburel ?

**Comment by jburel** [comment]
you won't be able to connect to 5.4.x server with the current 5.5.x insight.

**Comment by dominikl** [comment]
That's true... Gateway has the option to ignore version mismatch, but Insight actually doesn't. Guess that's alright then to remove this code.

**Comment by jburel** [comment]
Thanks

**Pull request merged**
