### PR TITLE
path error

### PR DESCRIPTION
**Pull request by jburel**
Select file to upload/import on Windows 10 
see https://github.com/ome/omero-insight/issues/146

cc @pwalczysko

### CODE REVIEW

**Comment by pwalczysko** [comment]
On Windows 10, I cannot repeat the original problem. 
From the QA report, the problem seems to be an insertion of a question mark into the path of the image.
But no idea how to create such situation. Tried to create a shortcut and import the shortcut. This failed with a different error.

```
loci.formats.UnknownFormatException: Unknown file format: C:\Users\User\Desktop\test-jm.tif - Shortcut.lnk
	at loci.formats.ImageReader.getReader(ImageReader.java:202)
	at loci.formats.ImageReader.setId(ImageReader.java:844)
...`
```

**Comment by jburel** [comment]
The error in that case is expected

**Comment by pwalczysko** [comment]
> The error in that case is expected
> Did a dialog pop up?

No, no dialog popped up. Note that I was using the release insight.

**Comment by dominikl** [comment]
Didn't get the "Cannot use shortcut..." dialog either. Just import fails with "Unknown file format". But doubt too that that's really the problem of https://github.com/ome/omero-insight/issues/146 (very weird path with `?` characters in the path name, etc.).

**Pull request closed without merging**
