### PR TITLE
Have Insight default to connecting securely.

### PR DESCRIPTION
**Pull request by mtbc**
I propose that it's better to have the padlock start off locked. Try starting up Insight and see how it's now set.

### CODE REVIEW

**Comment by jburel** [comment]
It certainly avoid the surprise we had in Singapore or with merge-ci

**Comment by jburel** [comment]
cc @pwalczysko

**Comment by mtbc** [comment]
Given caution raised by @jburel I experimented a little with how the `--encrypted` option affects CLI import of [77928.svs](https://downloads.openmicroscopy.org/images/SVS/77928.svs). The upload time slowdown for that was around 25%. I don't know how well one can generalize from that. (Heh, I notice I gave a HTTP**S** URL for the image file.)

**Comment by pwalczysko** [comment]
> It certainly avoids the surprise we had in Singapore or with merge-ci

I would think, however unpleasant these problems were, they are rather team-internal. Not sure about the new behaviour - speed of import means a lot

**Comment by jburel** [comment]
The speed of import is a major problem.
I think we should stick to the current default i.e. start with the padlock not locked

**Comment by joshmoore** [comment]
I don't know how hard it would be to do this in OMEROGateway, but an alternative would be to move to SSL as the default for everything _except_ importing. This would work due to https://github.com/openmicroscopy/openmicroscopy/pull/5645 which is that if SSL is _not_ enabled, the importer natively falls back to TCP.

**Comment by jburel** [comment]
I think we can look at that post 5.5 since it has been like that for a long time. So need to introduce extra work now

**Comment by mtbc** [comment]
Best to close at this time then; if somebody wants to pick up the work then they can cherry-pick the commit.

Might be nice if paranoid people *can* choose to import over SSL too even if not default.

**Comment by joshmoore** [comment]
> Might be nice if paranoid people can choose to import over SSL too even if not default.

That's the inverse logic, which would require checking. I _assume_ that setting the lock icon propagates down to import.

**Comment by jburel** [comment]
the lock icon means that any data transfer is "secured" including import

**Comment by joshmoore** [comment]
> the lock icon means that any data transfer is "secured" including import

Definitely know that's the intent. But with the automatic fallback, it probably would require a visual inspection of the log to know that it's working as intended.

**Pull request closed without merging**
